### PR TITLE
Finalization of Make-Team use case

### PR DESCRIPTION
**Pull request by mimischly7**
Includes creating a use-case Factory for my make-team usecase, enhancing the API interface (with slight refactorings), adding more appropriate implementations in the API data access object, creating a View for my use case and refactoring the ViewModel, and other small changes.

### CODE REVIEW

**Review by VicRendonMx — COMMENTED** [review]
The changes look solid. The change in the dependencies in pom.xml look use full for creating some other new methods. Also, the mocks you added will be useful more testing my comparison methods without calling the API and exhausting the API call attempts we have. 

After reading most of your additions, I can tell you that everything looks good. I even tried to run some of the stuff in my computer and it works. Thanks for the additions. I'll use this use case to change the functionality of mine and pulling. Thank you for adding comments so that I can understand the whole functionality of it. However, I remember the documentation.

**Review by samarthsharma411 — COMMENTED** [review]
Coding Style: The coding style corresponds with the one followed in the project and course throughout and proper naming conventions are used

Correctness: I have tried checking out the branch of code and testing it and it works.

Tests: There are tests present for some cases but not all, I believe you will add tests for all cases soon

CA+ Solid: The design perfectly follows the CA engine and SOLID design principles, through the use of small interfaces and factories.

Some stuff isn't clearly documented, I believe you will add documentation for this soon,

**Comment by pete8751** [comment]
The use case is perfectly functional, and adheres to the CA method and SOLID principles. As Sam and Victor have already stated, it could use a bit more documentation, just for extra readability. Your view looks solid, and is perfectly functional. One idea for the view however, would be to lie the components in a column, just to make things look a little more aesthetic - shouldn't be a large modification. 

Finally, I noticed in the APIDAO we are matching user inputs directly to player first and last names. Instead, we could try using regex to return players from the API that contain any groups of strings in the user's inputs. This could improve usability, as users wouldn't need to type their chosen player's name in perfectly.

This last change could be approached in another way than regex, and you know better than I would about how feasible it would be. Let me know if this idea works/if you have any different thoughts. 

Nice work.

**Review by pete8751 — APPROVED** [review]
The use case is perfectly functional, and adheres to the CA method and SOLID principles. As Sam and Victor have already stated, it could use a bit more documentation, just for extra readability. Your view looks solid, and is perfectly functional. One idea for the view however, would be to lie the components in a column, just to make things look a little more aesthetic - shouldn't be a large modification. 

Finally, I noticed in the APIDAO we are matching user inputs directly to player first and last names. Instead, we could try using regex to return players from the API that contain any groups of strings in the user's inputs. This could improve usability, as users wouldn't need to type their chosen player's name in perfectly.

This last change could be approached in another way than regex, and you know better than I would about how feasible it would be. Let me know if this idea works/if you have any different thoughts. 

Nice work.

**Pull request merged**
